apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.eventsubmissionservice.name }}
spec:
  replicas: {{ .Values.eventsubmissionservice.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.eventsubmissionservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.eventsubmissionservice.name }}
    spec:
      containers:
      - name: event-submission-service
        image: {{ .Values.imagestore.eventsubmission.repository }}:{{ .Values.imagestore.eventsubmission.tag }}
        env:
        - name: AMQP_URL
          value: {{ .Values.eventsubmissionservice.amqpurl }}
        - name: ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: transactionstoresecret
              key: accountName
        - name: ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: transactionstoresecret
              key: accountKey
