environment:
serviceAccount:
  adaptationname: adaptation-service-sa
  janitorname: pod-janitor-sa
volumemountpath:
  source: "/var/source"
  target: "/var/target"
queue:
  host:
    url: "rabbitmq-service"
    port: "\"5672\""
    #rabbitUserName is the name of the secret where the RabbitMQ user name is stored for conntecting with the message broker.
    #rabbitPassword is the name of the secret where the RabbitMQ password is stored for conntecting with the message broker.
  adaptationRequest:
    exchangename: "adaptation-exchange"
    requestqueuename: "adaptation-request-queue"
    replyqueuename: "amq.rabbitmq.reply-to"
    messagename: "adaptation-request"
adaptationservice:
  name: adaptation-service
  namespace: icap-adaptation
  replicas: 1
  amqpurl: "amqp://guest:guest@rabbitmq-service:5672/"
  rolename: adaptation-service-role
icapservice:
  name: mvp-icap-service
  applabel: adaptation
  replicas: 1
  port: 1344
icapserviceconfig:
  processingtimeoutduration: 00:01:00
podjanitor:
  name: pod-janitor
  namespace: icap-adaptation
  rolename: janitor-role
  deleteSuccessfulAfter: 1m
  deleteFailedAfter: 3m
eventsubmissionservice:
  name: event-submission-service
  replicas: 1
  amqpurl: "amqp://guest:guest@rabbitmq-service:5672/"
imagestore:
  requestprocessing:
    repository: glasswallsolutions/icap-request-processing
    tag: develop-81a7f9f
  adaptationservice:
    repository: glasswallsolutions/icap-adaptation-service
    tag: develop-330790c
  podjanitor:
    repository: glasswallsolutions/pod-janitor
    tag: develop-305e37e
  icapservice:
    repository: glasswallsolutions/mvp-icap-service
    tag: develop-65b8e04
  eventsubmission:
    repository: glasswallsolutions/event-submission-service
    tag: develop-457bea3
storage:
  class: azurefile
